### PR TITLE
update readme for property tag rename

### PR DESCRIPTION
**Pull request by oker1**

### CODE REVIEW

**Comment by agido-jrieks** [comment]
@oker1 thank you for your PR... I'm asking myself why the old configuration is then still working for me.

**Comment by agido-jrieks** [comment]
@oker1 I found the reason: ElasticsearchProperties.addProperty is called for the <property> tag, all it needs is to add a method addEsProperty to support that tag.

**Comment by agido-jrieks** [comment]
@oker1 I've reverted the EsProperty to Property renaming and added the addEsProperty method, I think this should be enough to make this work. We'll publish a version 3.0.6 with that change today.

**Comment by oker1** [comment]
thanks!

**Pull request merged**
